---
# tasks file for vikiscripts.bind9
- name: Install bind9
  apt: name=bind9 state=present

- name: Set hostname
  hostname:
    name: "{{ host_name }}"

- name: Set hostname fact
  set_fact:
    ansible_fqdn: "{{ host_name }}"

- name: Copy bind9 default config
  template:
    src: templates/default.bind9.j2
    dest: /etc/default/bind9
  notify: restart bind9

- name: Copy named conf options file
  template:
    src: templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9

- name: Copy named conf local file
  template:
    src: templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind9
 
- name: Make zones Directory
  file:
    path: /etc/bind/zones
    state: directory
    owner: root
    mode: 0750

- name: Copy forward file
  template:
    src: templates/db.forward.j2
    dest: /etc/bind/zones/db.{{ domain }}
    owner: root
    group: bind
    mode: 0640
  notify: restart bind9
  when:
    - ansible_dns_role == 'master'
    
- name: Copy reverse file
  template:
    src: templates/db.reverse.j2
    dest: /etc/bind/zones/db.{{ rev_domain }}
    owner: root
    group: bind
    mode: 0640
  notify: restart bind9
  when:
    - ansible_dns_role == 'master'
